version: '3.9'

networks:
  default:
    name: 'finansik'

volumes:
  finansik-pg:
  finansik-logs:
  finansik-prometheus:
  finansik-grafana:

services:
  postgres:
    container_name: 'finansik-pg'
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - finansik-pg:/var/lib/postgresql/data

  prometheus:
    container_name: 'finansik-prometheus'
    image: 'prom/prometheus'
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - finansik-prometheus:/prometheus
        
  loki:
    container_name: 'finansik-loki'
    image: 'grafana/loki'
    ports:
      - '3100:3100'
    volumes:
      - ./loki-config.yml:/mnt/config/loki-config.yaml
    command: --config.file=/mnt/config/loki-config.yaml
    
  grafana:
    container_name: 'finansik-grafana'
    image: 'grafana/grafana'
    restart: 'unless-stopped'
#    environment:
#      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - finansik-grafana:/var/lib/grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
  
  jaeger:
    container_name: 'finansik-jaeger'
    image: 'jaegertracing/all-in-one:1.59'
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    ports:
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
      - '14250:14250'
      - '14268:14268'
      - '14269:14269'
      - '9411:9411'
        
  api:
    build:
      context: .
    container_name: 'finansik-api'
    ports:
      - '8080:8080'
    environment:
      ConnectionStrings__Postgres: "User ID=postgres;Password=postgres;Host=finansik-pg;Port=5432;Database=finansik;Pooling=true;MinPoolSize=0;MaxPoolSize=100;Connection Idle Lifetime=60;"
      ConnectionStrings__Logs: "http://finansik-loki:3100"
      ConnectionStrings__Tracing: "http://finansik-jaeger:14268/api/traces"
        