version: '3.9'

networks:
  default:
    name: 'finansik'

volumes:
  finansik-pg:
  finansik-logs:
  finansik-prometheus:
  finansik-grafana:

services:
  postgres:
    container_name: 'finansik-pg'
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - finansik-pg:/var/lib/postgresql/data

  opensearch:
    container_name: 'finansik-opensearch'
    image: 'opensearchproject/opensearch:2'
    ports:
      - '9200:9200'
      - '9600:9600'
    environment:
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 'e16He]fK8)}R'
      discovery.type: 'single-node'
      plugins.security.disabled: true
    volumes:
      - finansik-logs:/usr/share/opensearch/data
  
  opensearch-dashboards:
    container_name: 'finansik-opensearch-dashboards'
    image: 'opensearchproject/opensearch-dashboards:latest'
    ports:
      - '5601:5601'
    environment:
      OPENSEARCH_HOSTS: '["http://finansik-opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
    depends_on:
      - opensearch

  prometheus:
    container_name: 'finansik-prometheus'
    image: 'prom/prometheus'
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - finansik-prometheus:/prometheus
  
  grafana:
    container_name: 'finansik-grafana'
    image: 'grafana/grafana'
    restart: 'unless-stopped'
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - finansik-grafana:/var/lib/grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus