scrape_configs:
  - job_name: finansik-scrape
    scrape_interval: 10s
    scrape_timeout: 3s
    static_configs: 
      - targets: 
          - finansik-api:8080
        labels: 
          app: finansik
    